name: fitizens
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1+4
  image_picker: ^0.8.4
  google_mlkit_commons: ^0.6.0
#    path: ../google_mlkit_commons
  google_mlkit_pose_detection: ^0.6.0
  google_mlkit: ^0.6.0
  path_provider: ^2.0.5
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.google_mlkit_pose_detection
        pluginClass: GoogleMlKitPoseDetectionPlugin
      ios:
        pluginClass: GoogleMlKitPoseDetectionPlugin