name: fitizens
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  image_picker: ^0.8.4
  path_provider: ^2.0.5
  path: ^1.8.2
  google_ml_kit: ^0.16.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.google_mlkit_pose_detection
        pluginClass: GoogleMlKitPoseDetectionPlugin
      ios:
        pluginClass: GoogleMlKitPoseDetectionPlugin