name: fitizens
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^6.5.9
  mdsflutter: ^2.0.0
  shared_preferences: ^2.2.2
  permission_handler: ^10.4.3
  provider: ^6.1.1
  google_mlkit_commons: ^0.6.1
  image_picker: ^1.0.4
  path: ^1.8.3
  path_provider: ^2.1.1
  camera: ^0.10.5+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
